[versions]
# Warning: this file is used as build trigger, do not add anything else here!
lowkeyVault = "2.11.0"

[libraries]
lowkey-vault-app = { module = "com.github.nagyesta.lowkey-vault:lowkey-vault-app", version.ref = "lowkeyVault" }

[bundles]

[plugins]
